apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: cephfs
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: QVFBQXZWSmNXK0Z1SnhBQWkwTGxaM0tYMHlNRTFUQXZPNlJNK2c9PQ==

